---
title: "Join the lab"
---

Our lab is always interested in welcoming motivated people interested in:

- Thermal and hydric biology
- Physiological ecology  
- Evolutionary physiology  
- Quantitative synthesis (meta-analysis)

If you are interested in joining the lab (undergraduate, graduate, or postdoctoral), please get in touch via email with a brief description of your interests and background.

---

# Mentoring phylosophy

Our approach to mentoring integrates physiology, ecology, and evolutionary biology through a quantitative and organismal perspective. We emphasise critical thinking, experimental design, data analysis, and writing, with the ultimate aim to equip students with the tools necessary to investigate biological questions across levels of organisation as well as efficiently communicate their research to a broader audience. 

We are committed to training students at all levels, from undergraduate research projects to graduate supervision. We adopt an active-learning approach, combining conceptual and data-driven discussions. 

---

# Contact information

Prof. Danilo Giacometti, PhD | [dgiacometti@usp.br](mailto:dgiacometti@usp.br)

**Laboratory of Integrative Physiology and Animal Performance (LaFIDA)**

Department of Physiology, Institute of Biosciences  
University of São Paulo
São Paulo, Brasil